services:
  - type: web
    name: alliance-ai-python-backend
    env: docker
    buildCommand: pip install -r backend-deploy/requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
    dockerfilePath: ./Dockerfile
